[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[bacula-client]
source = "cmd"
cmd = 'curl -I https://sourceforge.net/projects/bacula/files/latest/download | grep location | cut -d "/" -f 7'

[dieharder]
source = "github"
github = "christopherkobayashi/dieharder"
use_latest_release = true

[entropy-assessment]
source = "github"
github = "usnistgov/SP800-90B_EntropyAssessment"
use_latest_release = true
prefix = "v"

[google-earth-pro]
source = "cmd"
cmd = '''curl -sL https://dl.google.com/linux/earth/deb/dists/stable/main/binary-amd64/Packages | grep -Pom1 'Version: \K[^-]*''''

[huestacean]
source = "github"
github = "BradyBrenot/huestacean"
use_latest_release = true
prefix = "v"

[intel-ipsec-mb]
source = "github"
github = "intel/intel-ipsec-mb"
use_latest_release = true
prefix = "v"

[jk2mv]
source = "github"
github = "mvdevs/jk2mv"
use_latest_release = true

[jupyter-metakernel]
source = "github"
github = "Calysto/metakernel"
use_latest_release = true
prefix = "v"

[jupyter-octave_kernel]
source = "github"
github = "Calysto/octave_kernel"
use_latest_release = true
prefix = "v"

[kaobook]
source = "github"
github = "fmarotta/kaobook"
use_latest_release = true

[kde-servicemenus-encfs]
source = "regex"
url = "https://www.egregorion.net/"
regex = "KDE 5 Service Menu EncFS v([\\d]\\.[\\d])"

[kdeplasma-applets-fokus]
source = "gitlab"
gitlab = "divinae/focus-plasmoid"
use_max_tag = true
prefix = "v"

[liboqs]
source = "github"
github = "open-quantum-safe/liboqs"
use_latest_release = true

[linux-enable-ir-emitter]
source = "github"
github = "EmixamPP/linux-enable-ir-emitter"
use_latest_release = true

[mssql-cli]
source = "github"
github = "dbcli/mssql-cli"
use_latest_release = true

[nist-sts]
source = "cmd"
cmd = "curl -s https://csrc.nist.gov/Projects/Random-Bit-Generation/Documentation-and-Software | grep 'Download</a>' | cut -d '.' -f 1 | cut -d '-' -f 4 | sed 's/_/./g'"

[oqsprovider]
source = "github"
github = "open-quantum-safe/oqs-provider"
prefix = "v"
use_latest_release = true

[python-comparxiv]
source = "github"
github = "temken/comparxiv"
use_latest_release = true
prefix = "v"

[python-constraint]
source = "github"
github = "python-constraint/python-constraint"
use_latest_release = true

[python-dlx]
source = "pypi"
pypi = "dlx"

[python-docplex]
source = "pypi"
pypi = "docplex"

[python-dwdweather2]
source = "github"
github = "panodata/dwdweather2"
use_latest_tag = true

[python-galois]
source = "pypi"
pypi = "galois"

[python-ibm-platform-services]
source = "github"
github = "IBM/platform-services-python-sdk"
use_latest_release = true
prefix = "v"

[python-marshmallow-polyfield]
source = "pypi"
pypi = "marshmallow-polyfield"

[python-multiset]
source = "pypi"
pypi = "multiset"

[python-multitasking]
source = "pypi"
pypi = "multitasking"

[python-projectq]
source = "github"
github = "ProjectQ-Framework/ProjectQ"
use_latest_release = true
prefix = "v"

[python-pydes]
source = "pypi"
pypi = "pyDes"

[python-qiskit]
source = "github"
github = "Qiskit/qiskit"
use_latest_release = true

[python-qiskit-aer]
source = "github"
github = "Qiskit/qiskit-aer"
use_latest_release = true

[python-qiskit-dynamics]
source = "github"
github = "Qiskit/qiskit-dynamics"
use_latest_release = true

[python-qiskit-experiments]
source = "github"
github = "Qiskit/qiskit-experiments"
use_latest_release = true

[python-qiskit-finance]
source = "github"
github = "Qiskit/qiskit-finance"
use_latest_release = true

[python-qiskit-ibm-experiment]
source = "github"
github = "Qiskit/qiskit-ibm-experiment"
use_max_tag = true

[python-qiskit-ibm-runtime]
source = "github"
github = "Qiskit/qiskit-ibm-runtime"
use_latest_release = true

[python-qiskit-ibmq-provider]
source = "github"
github = "Qiskit/qiskit-ibmq-provider"
use_latest_release = true

[python-qiskit-ignis]
source = "github"
github = "Qiskit/qiskit-ignis"
use_latest_release = true

[python-qiskit-machine-learning]
source = "github"
github = "Qiskit/qiskit-machine-learning"
use_latest_release = true

[python-qiskit-nature]
source = "github"
github = "Qiskit/qiskit-nature"
use_latest_release = true

[python-qiskit-optimization]
source = "github"
github = "Qiskit/qiskit-optimization"
use_latest_release = true

[python-qiskit-terra]
source = "github"
github = "Qiskit/qiskit-terra"
use_latest_release = true

[python-rustworkx]
source = "github"
github = "Qiskit/rustworkx"
use_latest_release = true

[python-tweedledum]
source = "pypi"
pypi = "tweedledum"

[python-yfinance]
source = "github"
github = "ranaroussi/yfinance"
use_latest_release = true

[rpi-imager]
source = "github"
github = "raspberrypi/rpi-imager"
use_latest_release = true
prefix = "v"

[scute]
source = "git"
git = "https://dev.gnupg.org/source/scute.git"
prefix = "scute-"

[slack-export-viewer]
source = "github"
github = "hfaran/slack-export-viewer"
use_latest_release = true

[slackdump]
source = "github"
github = "rusq/slackdump"
use_latest_release = true
prefix = "v"

[spectre-meltdown-checker]
source = "github"
github = "speed47/spectre-meltdown-checker"
use_latest_release = true
prefix = "v"

[stress-ng]
source = "github"
github = "ColinIanKing/stress-ng"
use_latest_tag = true
prefix = "V"

[sts]
source = "github"
github = "arcetri/sts"
use_latest_tag = true
